# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Authorization: Token 8bdfc96077c98f9378e6fe936c637f127d474c51
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 5278b96b5af2fdf779f54ab5b22d6399ba44d6db

{
  "title": "опора",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token 5278b96b5af2fdf779f54ab5b22d6399ba44d6db

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

### добавить в избранное
GET {{baseUrl}}/advertisements/1/favorites
Content-Type: application/json
Authorization: Token 8bdfc96077c98f9378e6fe936c637f127d474c51

### удалить избранное
DELETE {{baseUrl}}/advertisements/1/delete/
Authorization: Token 8bdfc96077c98f9378e6fe936c637f127d474c51

### получить список избранных обьяв
GET {{baseUrl}}/advertisements/favorites_posts
Content-Type: application/json
Authorization: Token 8bdfc96077c98f9378e6fe936c637f127d474c51